### PR TITLE
add support for single quotes (issue #50)

### PR DESCRIPTION
**Pull request by faceyspacey**

### CODE REVIEW

**Comment by faceyspacey** [comment]
thanks brother. Do you mind publishing to NPM

**Comment by yury** [comment]
I’ll push on Monday

**Comment by faceyspacey** [comment]
I actually got this wrong. '`' needs to append one space after the content that follow. Eg:

```
' foo'
bar
```
->
```
foo bar
```

I'm not exactly sure how to do this one. Any guesses?

**Comment by faceyspacey** [comment]
From the docs:

###Verbatim text with trailing white space `'`
*The single quote tells Slim to copy the line (similar to |), but makes sure that a single trailing white space is appended.*

http://www.rubydoc.info/gems/slim/frames#Verbatim_text_with_trailing_white_space__

**Comment by yury** [comment]
Take a look at `.`, it works

**Comment by faceyspacey** [comment]
I PRed an option for both: 

https://github.com/slm-lang/slm/pull/52/files#diff-3fab227e34d65fe9bb2d6ea53eec41cfR217

...but im not sure if there are other considerations. it does work for basic examples.

**Pull request merged**
